language: node_js
node_js:
- '7'
- '8'
- '9'
notifications:
  slack:
    secure: ZCRTDfunZPohsybKadHEeMQa61/LCVbsF+IekNBre4g5VTz8qkH83oOgr1AbXwvGJu+vvTeZesspYBjAc+aau+MZsi6HaHO+8aTJTpLxgaDo7isnEpM5ncbxU63NDZH/C9DNg6g6QHECMBK7IQshtlyCHRXK0LIY3WszlSElQ9IKKRoKawNIigijrbvVdD/+x3sP3ynYgzU/WXR3qpNQgO2f3RzIpVIlmiSRYwhQ4GnpwhdggLmPvoCmDMk4DQ49c6eqFyOTsu1waUDvj+qEmyc3ovkdGwDbaIrmKScXPfyLy8kPczbfxF0XvZsdvU5fVLY9/a85xwZqe8FPVApAjWnrcE9X9tfdmCJ93nlNfeqaikfVmhhPPno5UF0wc7aRYMBFqyJuMiLv2SXaABDkxVUNs2CLH1OOXLamvz/kGlEJaA4KS3cfZBHjSowXaI9zCWyH0Gb1rp23UPpDQ1dU+mXQX7rgb0eqiiBePI+HTao7TR0dghKsEmtCZsHbqVVKlMGqDuyrzXuBnWeTuaj0Qh49nxH814EFxvtABph2etxsPUnnz1u6mQJPcEF6NuGWH7J9vCRqLUs5rwDNS9YAINJcuLSORjYiZbNdBQYirxiklH1GD6eHYQQ/bLyy37p5Z8/6oajGWDB3rweVwCjTUdNC6SqJZ/5sY6qVNLgqE6U=
